version: 2
jobs:
  build:
    working_directory: ~/id3-charset-converter
    docker:
        - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: id3-charset-converter-{{ checksum "build.gradle" }}      
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
